# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.0.3 on 2022-03-17 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaselinkerAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254)),
                ("token", models.CharField(max_length=128)),
                ("base_url", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="BaselinkerOrderStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.CharField(editable=False, max_length=100)),
                ("external_data", models.JSONField(blank=True, editable=False, null=True)),
                ("is_active", models.BooleanField(default=True, editable=False)),
                ("inactive_since", models.DateTimeField(blank=True, editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_statuses",
                        to="django_baselinker.baselinkeraccount",
                        verbose_name="Baselinker account",
                    ),
                ),
            ],
            options={"verbose_name": "Baselinker status", "verbose_name_plural": "Baselinker statuses"},
        ),
        migrations.CreateModel(
            name="BaselinkerOrderSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(max_length=20)),
                ("source_id", models.IntegerField()),
                ("external_data", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("inactive_since", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_sources",
                        to="django_baselinker.baselinkeraccount",
                        verbose_name="Baselinker account",
                    ),
                ),
            ],
            options={"verbose_name": "Baselinker source", "verbose_name_plural": "Baselinker sources"},
        ),
        migrations.CreateModel(
            name="BaselinkerOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_order_id", models.CharField(blank=True, max_length=128, null=True)),
                ("baselinker_order_id", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="django_baselinker.baselinkeraccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BaselinkerEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("processed", "Processed"), ("failed", "Failed"), ("new", "New")], max_length=16
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("log_id", models.IntegerField()),
                ("log_type", models.IntegerField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="django_baselinker.baselinkeraccount",
                        verbose_name="Baselinker account",
                    ),
                ),
            ],
            options={"ordering": ["created_at", "updated_at"]},
        ),
        migrations.AddConstraint(
            model_name="baselinkerordersource",
            constraint=models.UniqueConstraint(fields=("source", "source_id"), name="source_id_unique_per_source"),
        ),
    ]
